(princ "Arithematic operations")
(terpri)
(princ "Enter two numbers to add : ")
(write (+ (read) (read) ))
(terpri)
(princ "Enter two numbers to subtract : ")
(write (- (read)  (read) ))
(terpri)
(princ "Enter two numbers to multiply : ")
(write (* (read) (read) ))
(terpri)
(princ "Enter two numbers to divide : ")
(write (/ (read) (read) ))
(terpri)