(setf a "Mini")
(setf b "Assignment-1")
(setf c "Lisp is cool")

(print (length c))
(terpri)
(print (subseq c 5 7))
(terpri)
(print (concatenate 'string a b))
(terpri)
(print (sort (vector a b c) 'string<))
(terpri)
(write (reverse c))
(terpri)